DEFAULT_GROUP_BOX_AUTO_CROP = True
DEFAULT_GROUP_BOX_FIXED_SIZE = False
DEFAULT_SPIN_BOX_SIZE_X = 5000
DEFAULT_SPIN_BOX_SIZE_Y = 5000
DEFAULT_SPIN_BOX_MAX_SIDE_LENGTH = 5000
DEFAULT_SPIN_BOX_MARGIN = 100
DEFAULT_SPIN_BOX_COMPONENT_RADIUS = 5
DEFAULT_CANVAS_COLOR = "#540144"




