# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 646)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/feather-white/pcb-board.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("* {\n"
"    font: 9pt \"Segoe UI\";\n"
"}\n"
"\n"
"QMainWindow, QFrame, QStatusBar {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QScrollBar:down-arrow, QScrollBar:add-line, QScrollBar:up-arrow, QScrollBar:sub-line {\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width: 10px;\n"
"    border-radius:3px;\n"
"    background-color: rgb(231, 233, 234);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(138, 147, 155);\n"
"    border-radius:3px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 10px;\n"
"    border-radius:3px;\n"
"    background-color: rgb(231, 233, 234);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(138, 147, 155);\n"
"    border-radius:3px;\n"
"    margin: 2px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.frameWindow = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameWindow.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frameWindow.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameWindow.setObjectName("frameWindow")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frameWindow)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(parent=self.frameWindow)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonLoadFile = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButtonLoadFile.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonLoadFile.setStyleSheet(".QPushButton {\n"
"    padding: 4px 6px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/feather-white/file-text.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLoadFile.setIcon(icon1)
        self.pushButtonLoadFile.setObjectName("pushButtonLoadFile")
        self.gridLayout_2.addWidget(self.pushButtonLoadFile, 0, 0, 1, 1)
        self.lineEditFilePath = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEditFilePath.setMouseTracking(False)
        self.lineEditFilePath.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEditFilePath.setReadOnly(True)
        self.lineEditFilePath.setObjectName("lineEditFilePath")
        self.gridLayout_2.addWidget(self.lineEditFilePath, 0, 1, 1, 1)
        self.pushButtonOpenInExplorer = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButtonOpenInExplorer.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonOpenInExplorer.setStyleSheet(".QPushButton {\n"
"    padding: 4px 6px;\n"
"}")
        self.pushButtonOpenInExplorer.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/feather-white/external-link.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonOpenInExplorer.setIcon(icon2)
        self.pushButtonOpenInExplorer.setObjectName("pushButtonOpenInExplorer")
        self.gridLayout_2.addWidget(self.pushButtonOpenInExplorer, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frameWorkspace = QtWidgets.QFrame(parent=self.frameWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameWorkspace.sizePolicy().hasHeightForWidth())
        self.frameWorkspace.setSizePolicy(sizePolicy)
        self.frameWorkspace.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frameWorkspace.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameWorkspace.setObjectName("frameWorkspace")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frameWorkspace)
        self.gridLayout_9.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_9.setSpacing(5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.splitter = QtWidgets.QSplitter(parent=self.frameWorkspace)
        self.splitter.setStyleSheet(" QSplitter::handle {\n"
"    background-color: #ebecf0;\n"
"    margin: 0px 5px;\n"
"}")
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.frame_4 = QtWidgets.QFrame(parent=self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_6.setStyleSheet(".QPushButton:checked {\n"
"    background-color: #dce6f2;\n"
"}\n"
".QPushButton {\n"
"    border: 1px solid #e8e8e8;\n"
"    border-radius: 5px;\n"
"    padding: 4px 6px;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.labelTextLinId = QtWidgets.QLabel(parent=self.frame_6)
        self.labelTextLinId.setStyleSheet("font-weight: bold;\n"
"padding: 2px;")
        self.labelTextLinId.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelTextLinId.setObjectName("labelTextLinId")
        self.gridLayout_10.addWidget(self.labelTextLinId, 2, 0, 1, 1)
        self.comboBoxLineId = QtWidgets.QComboBox(parent=self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxLineId.sizePolicy().hasHeightForWidth())
        self.comboBoxLineId.setSizePolicy(sizePolicy)
        self.comboBoxLineId.setObjectName("comboBoxLineId")
        self.gridLayout_10.addWidget(self.comboBoxLineId, 2, 1, 1, 1)
        self.labelTextPanelId = QtWidgets.QLabel(parent=self.frame_6)
        self.labelTextPanelId.setStyleSheet("font-weight: bold;\n"
"padding: 2px;")
        self.labelTextPanelId.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelTextPanelId.setObjectName("labelTextPanelId")
        self.gridLayout_10.addWidget(self.labelTextPanelId, 3, 0, 1, 1)
        self.comboBoxPanelId = QtWidgets.QComboBox(parent=self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPanelId.sizePolicy().hasHeightForWidth())
        self.comboBoxPanelId.setSizePolicy(sizePolicy)
        self.comboBoxPanelId.setObjectName("comboBoxPanelId")
        self.gridLayout_10.addWidget(self.comboBoxPanelId, 3, 1, 1, 1)
        self.labelIdno_2 = QtWidgets.QLabel(parent=self.frame_6)
        self.labelIdno_2.setStyleSheet("font-weight: bold;\n"
"padding: 2px;")
        self.labelIdno_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelIdno_2.setObjectName("labelIdno_2")
        self.gridLayout_10.addWidget(self.labelIdno_2, 1, 0, 1, 1)
        self.labelIdno = QtWidgets.QLabel(parent=self.frame_6)
        self.labelIdno.setStyleSheet("font-weight: bold;\n"
"padding: 2px;")
        self.labelIdno.setText("")
        self.labelIdno.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelIdno.setObjectName("labelIdno")
        self.gridLayout_10.addWidget(self.labelIdno, 1, 1, 1, 1)
        self.labelTextProduct = QtWidgets.QLabel(parent=self.frame_6)
        self.labelTextProduct.setStyleSheet("font-weight: bold;\n"
"padding: 2px;")
        self.labelTextProduct.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelTextProduct.setObjectName("labelTextProduct")
        self.gridLayout_10.addWidget(self.labelTextProduct, 0, 0, 1, 1)
        self.labelProduct = QtWidgets.QLabel(parent=self.frame_6)
        self.labelProduct.setStyleSheet("font-weight: bold;\n"
"padding: 2px;")
        self.labelProduct.setText("")
        self.labelProduct.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelProduct.setObjectName("labelProduct")
        self.gridLayout_10.addWidget(self.labelProduct, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame_6, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_5.setStyleSheet(".QPushButton:checked {\n"
"    background-color: #dce6f2;\n"
"}\n"
".QPushButton {\n"
"    border: 1px solid #e8e8e8;\n"
"    border-radius: 5px;\n"
"    padding: 4px 6px;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButtonSelectId = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButtonSelectId.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButtonSelectId.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonSelectId.setStyleSheet("")
        self.pushButtonSelectId.setCheckable(True)
        self.pushButtonSelectId.setAutoRepeat(True)
        self.pushButtonSelectId.setAutoExclusive(True)
        self.pushButtonSelectId.setObjectName("pushButtonSelectId")
        self.gridLayout_5.addWidget(self.pushButtonSelectId, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButtonSelectSize = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButtonSelectSize.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButtonSelectSize.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonSelectSize.setStyleSheet("")
        self.pushButtonSelectSize.setCheckable(True)
        self.pushButtonSelectSize.setChecked(True)
        self.pushButtonSelectSize.setAutoRepeat(False)
        self.pushButtonSelectSize.setAutoExclusive(True)
        self.pushButtonSelectSize.setObjectName("pushButtonSelectSize")
        self.gridLayout_5.addWidget(self.pushButtonSelectSize, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_5, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        self.label.setStyleSheet("font-weight: bold;\n"
"padding: 2px;")
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 3, 0, 1, 1)
        self.stackedWidgetSelectionMode = QtWidgets.QStackedWidget(parent=self.frame_4)
        self.stackedWidgetSelectionMode.setObjectName("stackedWidgetSelectionMode")
        self.pageSelectSize = QtWidgets.QWidget()
        self.pageSelectSize.setObjectName("pageSelectSize")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.pageSelectSize)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.treeWidgetSelectSize = CheckableTreeWidget(parent=self.pageSelectSize)
        self.treeWidgetSelectSize.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.treeWidgetSelectSize.setStyleSheet("QTreeWidget {\n"
"    border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"")
        self.treeWidgetSelectSize.setObjectName("treeWidgetSelectSize")
        self.treeWidgetSelectSize.headerItem().setText(0, "1")
        self.gridLayout_6.addWidget(self.treeWidgetSelectSize, 0, 0, 1, 1)
        self.stackedWidgetSelectionMode.addWidget(self.pageSelectSize)
        self.pageSelectId = QtWidgets.QWidget()
        self.pageSelectId.setObjectName("pageSelectId")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pageSelectId)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.treeWidgetSelectId = CheckableTreeWidget(parent=self.pageSelectId)
        self.treeWidgetSelectId.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.treeWidgetSelectId.setStyleSheet("QTreeWidget {\n"
"    border: 1px solid #e8e8e8;\n"
"}")
        self.treeWidgetSelectId.setObjectName("treeWidgetSelectId")
        self.treeWidgetSelectId.headerItem().setText(0, "1")
        self.gridLayout_8.addWidget(self.treeWidgetSelectId, 0, 0, 1, 1)
        self.stackedWidgetSelectionMode.addWidget(self.pageSelectId)
        self.gridLayout_7.addWidget(self.stackedWidgetSelectionMode, 5, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.frame_4)
        self.line.setStyleSheet("border: none;\n"
"border-bottom: 1px solid #e8e8e8;\n"
"padding: 5px 0px;")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsView = CustomGraphicsView(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.graphicsView.setStyleSheet("QGraphicsView {\n"
"    background-color: transparent;\n"
"    border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"/* 垂直水平捲軸設定 */\n"
"QScrollBar:down-arrow, QScrollBar:add-line, QScrollBar:up-arrow, QScrollBar:sub-line {\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width: 10px;\n"
"    border-radius:3px;\n"
"    background-color: rgb(231, 233, 234);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(138, 147, 155);\n"
"    border-radius:3px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 10px;\n"
"    border-radius:3px;\n"
"    background-color: rgb(231, 233, 234);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(138, 147, 155);\n"
"    border-radius:3px;\n"
"    margin: 2px;\n"
"}")
        self.graphicsView.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frameWorkspace, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frameWindow, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 895, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(parent=self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSetCanvas = QtGui.QAction(parent=MainWindow)
        self.actionSetCanvas.setObjectName("actionSetCanvas")
        self.menuSettings.addAction(self.actionSetCanvas)
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidgetSelectionMode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SPI Visualization Tool"))
        self.pushButtonLoadFile.setToolTip(_translate("MainWindow", "Load Excel / Csv File"))
        self.pushButtonLoadFile.setText(_translate("MainWindow", "Load File"))
        self.pushButtonOpenInExplorer.setToolTip(_translate("MainWindow", "Open In Explorer"))
        self.labelTextLinId.setText(_translate("MainWindow", "Line ID : "))
        self.labelTextPanelId.setText(_translate("MainWindow", "Panel ID : "))
        self.labelIdno_2.setText(_translate("MainWindow", "IDNO : "))
        self.labelTextProduct.setText(_translate("MainWindow", "Product : "))
        self.pushButtonSelectId.setText(_translate("MainWindow", "ID"))
        self.pushButtonSelectSize.setText(_translate("MainWindow", "Size"))
        self.label.setText(_translate("MainWindow", "Component Selection Mode : "))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionSetCanvas.setText(_translate("MainWindow", "Canvas"))
from src.Views.CustomWidgets.CheckableTreeWidget import CheckableTreeWidget
from src.Views.CustomWidgets.CustomGraphicsView import CustomGraphicsView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
