# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 646)
        MainWindow.setStyleSheet("* {\n"
"    font: 9pt \"Segoe UI\";\n"
"}\n"
"\n"
"QMainWindow, QFrame, QStatusBar {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QScrollBar:down-arrow, QScrollBar:add-line, QScrollBar:up-arrow, QScrollBar:sub-line {\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width: 10px;\n"
"    border-radius:3px;\n"
"    background-color: rgb(231, 233, 234);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(138, 147, 155);\n"
"    border-radius:3px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 10px;\n"
"    border-radius:3px;\n"
"    background-color: rgb(231, 233, 234);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(138, 147, 155);\n"
"    border-radius:3px;\n"
"    margin: 2px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.frameWindow = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameWindow.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frameWindow.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameWindow.setObjectName("frameWindow")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frameWindow)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(parent=self.frameWindow)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonLoadFile = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButtonLoadFile.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonLoadFile.setStyleSheet(".QPushButton {\n"
"    padding: 4px 6px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/feather-white/file-text.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLoadFile.setIcon(icon)
        self.pushButtonLoadFile.setObjectName("pushButtonLoadFile")
        self.gridLayout_2.addWidget(self.pushButtonLoadFile, 0, 0, 1, 1)
        self.lineEditFilePath = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEditFilePath.setMouseTracking(False)
        self.lineEditFilePath.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEditFilePath.setReadOnly(True)
        self.lineEditFilePath.setObjectName("lineEditFilePath")
        self.gridLayout_2.addWidget(self.lineEditFilePath, 0, 1, 1, 1)
        self.pushButtonOpenInExplorer = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButtonOpenInExplorer.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonOpenInExplorer.setStyleSheet(".QPushButton {\n"
"    padding: 4px 6px;\n"
"}")
        self.pushButtonOpenInExplorer.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/feather-white/external-link.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonOpenInExplorer.setIcon(icon1)
        self.pushButtonOpenInExplorer.setObjectName("pushButtonOpenInExplorer")
        self.gridLayout_2.addWidget(self.pushButtonOpenInExplorer, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.frameWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(parent=self.frame_3)
        self.splitter.setStyleSheet(" QSplitter::handle {\n"
"    background-color: #ebecf0;\n"
"    margin: 0px 5px;\n"
"}")
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.frame_4 = QtWidgets.QFrame(parent=self.splitter)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        self.label.setStyleSheet("font-weight: bold;\n"
"padding: 2px;")
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_5.setStyleSheet(".QPushButton:checked {\n"
"    background-color: #dce6f2;\n"
"}\n"
".QPushButton {\n"
"    border: 1px solid #e8e8e8;\n"
"    border-radius: 5px;\n"
"    padding: 4px 6px;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButtonSelectType = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButtonSelectType.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButtonSelectType.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonSelectType.setStyleSheet("")
        self.pushButtonSelectType.setCheckable(True)
        self.pushButtonSelectType.setChecked(True)
        self.pushButtonSelectType.setAutoRepeat(False)
        self.pushButtonSelectType.setAutoExclusive(True)
        self.pushButtonSelectType.setObjectName("pushButtonSelectType")
        self.gridLayout_5.addWidget(self.pushButtonSelectType, 1, 0, 1, 1)
        self.pushButtonSelectId = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButtonSelectId.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButtonSelectId.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonSelectId.setStyleSheet("")
        self.pushButtonSelectId.setCheckable(True)
        self.pushButtonSelectId.setAutoRepeat(True)
        self.pushButtonSelectId.setAutoExclusive(True)
        self.pushButtonSelectId.setObjectName("pushButtonSelectId")
        self.gridLayout_5.addWidget(self.pushButtonSelectId, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 2, 1, 1)
        self.gridLayout_7.addWidget(self.frame_5, 1, 0, 1, 1)
        self.stackedWidgetSelectionMode = QtWidgets.QStackedWidget(parent=self.frame_4)
        self.stackedWidgetSelectionMode.setObjectName("stackedWidgetSelectionMode")
        self.pageSelectType = QtWidgets.QWidget()
        self.pageSelectType.setObjectName("pageSelectType")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.pageSelectType)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.treeWidgetSelectType = CheckableTreeWidget(parent=self.pageSelectType)
        self.treeWidgetSelectType.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.treeWidgetSelectType.setStyleSheet("QTreeWidget {\n"
"    border: 1px solid #e8e8e8;\n"
"}")
        self.treeWidgetSelectType.setObjectName("treeWidgetSelectType")
        self.treeWidgetSelectType.headerItem().setText(0, "1")
        self.gridLayout_6.addWidget(self.treeWidgetSelectType, 0, 0, 1, 1)
        self.stackedWidgetSelectionMode.addWidget(self.pageSelectType)
        self.pageSelectId = QtWidgets.QWidget()
        self.pageSelectId.setObjectName("pageSelectId")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pageSelectId)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.treeWidgetSelectId = CheckableTreeWidget(parent=self.pageSelectId)
        self.treeWidgetSelectId.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.treeWidgetSelectId.setStyleSheet("QTreeWidget {\n"
"    border: 1px solid #e8e8e8;\n"
"}")
        self.treeWidgetSelectId.setObjectName("treeWidgetSelectId")
        self.treeWidgetSelectId.headerItem().setText(0, "1")
        self.gridLayout_8.addWidget(self.treeWidgetSelectId, 0, 0, 1, 1)
        self.stackedWidgetSelectionMode.addWidget(self.pageSelectId)
        self.gridLayout_7.addWidget(self.stackedWidgetSelectionMode, 2, 0, 1, 1)
        self.graphicsView = CustomGraphicsView(parent=self.splitter)
        self.graphicsView.setStyleSheet("QGraphicsView {\n"
"    background-color: transparent;\n"
"    border: 1px solid #e8e8e8;\n"
"}\n"
"\n"
"/* 垂直水平捲軸設定 */\n"
"QScrollBar:down-arrow, QScrollBar:add-line, QScrollBar:up-arrow, QScrollBar:sub-line {\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width: 10px;\n"
"    border-radius:3px;\n"
"    background-color: rgb(231, 233, 234);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(138, 147, 155);\n"
"    border-radius:3px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 10px;\n"
"    border-radius:3px;\n"
"    background-color: rgb(231, 233, 234);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(138, 147, 155);\n"
"    border-radius:3px;\n"
"    margin: 2px;\n"
"}")
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frameWindow, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.stackedWidgetSelectionMode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonLoadFile.setToolTip(_translate("MainWindow", "Load Excel / Csv File"))
        self.pushButtonLoadFile.setText(_translate("MainWindow", "Load File"))
        self.pushButtonOpenInExplorer.setToolTip(_translate("MainWindow", "Open In Explorer"))
        self.label.setText(_translate("MainWindow", "Component Selection Mode : "))
        self.pushButtonSelectType.setText(_translate("MainWindow", "Type"))
        self.pushButtonSelectId.setText(_translate("MainWindow", "ID"))
from src.Views.CustomWidgets.CheckableTreeWidget import CheckableTreeWidget
from src.Views.CustomWidgets.CustomGraphicsView import CustomGraphicsView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
