# Form implementation generated from reading ui file 'setting_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        SettingDialog.setObjectName("SettingDialog")
        SettingDialog.resize(554, 310)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingDialog.sizePolicy().hasHeightForWidth())
        SettingDialog.setSizePolicy(sizePolicy)
        SettingDialog.setMinimumSize(QtCore.QSize(0, 0))
        SettingDialog.setStyleSheet("* {\n"
"    font: 9pt \"Segoe UI\";\n"
"}\n"
"\n"
"QScrollBar:down-arrow, QScrollBar:add-line, QScrollBar:up-arrow, QScrollBar:sub-line {\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width: 10px;\n"
"    border-radius:3px;\n"
"    background-color: rgb(231, 233, 234);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(138, 147, 155);\n"
"    border-radius:3px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 10px;\n"
"    border-radius:3px;\n"
"    background-color: rgb(231, 233, 234);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(138, 147, 155);\n"
"    border-radius:3px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"\n"
"QSpinBox {\n"
"    border: 1px solid rgb(221, 221, 221);\n"
"    padding: 4px 4px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"     image: url(:/icons/feather-white/chevron-up);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"     image: url(:/icons/feather-white/chevron-down);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(SettingDialog)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(parent=SettingDialog)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.buttonBoxDialog = QtWidgets.QDialogButtonBox(parent=self.frame_5)
        self.buttonBoxDialog.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBoxDialog.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBoxDialog.setObjectName("buttonBoxDialog")
        self.gridLayout_9.addWidget(self.buttonBoxDialog, 0, 2, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.pushButtonReset = QtWidgets.QPushButton(parent=self.frame_5)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/feather-white/refresh-cw.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonReset.setIcon(icon)
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.gridLayout_9.addWidget(self.pushButtonReset, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_5, 1, 0, 1, 2)
        self.frame_6 = QtWidgets.QFrame(parent=SettingDialog)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.graphicsView = CanvasDemoGraphicsView(parent=self.frame_6)
        self.graphicsView.setMinimumSize(QtCore.QSize(200, 0))
        self.graphicsView.setStyleSheet("QGraphicsView {\n"
"    background-color: transparent;\n"
"    border: 1px solid #d8d8d8;\n"
"}")
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_8.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_6, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=SettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBoxAutoCrop = QtWidgets.QGroupBox(parent=self.frame_3)
        self.groupBoxAutoCrop.setStyleSheet("")
        self.groupBoxAutoCrop.setFlat(False)
        self.groupBoxAutoCrop.setCheckable(True)
        self.groupBoxAutoCrop.setObjectName("groupBoxAutoCrop")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxAutoCrop)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.groupBoxAutoCrop)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(140, 0))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.spinBoxMaxSideLength = QtWidgets.QSpinBox(parent=self.frame_2)
        self.spinBoxMaxSideLength.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBoxMaxSideLength.setMinimum(100)
        self.spinBoxMaxSideLength.setMaximum(20000)
        self.spinBoxMaxSideLength.setSingleStep(1)
        self.spinBoxMaxSideLength.setProperty("value", 5000)
        self.spinBoxMaxSideLength.setObjectName("spinBoxMaxSideLength")
        self.gridLayout_2.addWidget(self.spinBoxMaxSideLength, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBoxAutoCrop, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setStyleSheet(".QPushButton {\n"
"    border: none;\n"
"    margin: 1px;\n"
"\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_4.setMinimumSize(QtCore.QSize(140, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.spinBoxMargin = QtWidgets.QSpinBox(parent=self.frame_4)
        self.spinBoxMargin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBoxMargin.setMinimum(10)
        self.spinBoxMargin.setMaximum(1000)
        self.spinBoxMargin.setObjectName("spinBoxMargin")
        self.gridLayout_7.addWidget(self.spinBoxMargin, 0, 1, 1, 1)
        self.pushButtonBackgroundColor = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButtonBackgroundColor.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButtonBackgroundColor.setAutoFillBackground(False)
        self.pushButtonBackgroundColor.setStyleSheet("background-color: #540144;\n"
"")
        self.pushButtonBackgroundColor.setText("")
        self.pushButtonBackgroundColor.setObjectName("pushButtonBackgroundColor")
        self.gridLayout_7.addWidget(self.pushButtonBackgroundColor, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_6.setMinimumSize(QtCore.QSize(140, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 1, 0, 1, 1)
        self.spinBoxComponentRadius = QtWidgets.QSpinBox(parent=self.frame_4)
        self.spinBoxComponentRadius.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBoxComponentRadius.setMinimum(1)
        self.spinBoxComponentRadius.setMaximum(1000)
        self.spinBoxComponentRadius.setProperty("value", 10)
        self.spinBoxComponentRadius.setObjectName("spinBoxComponentRadius")
        self.gridLayout_7.addWidget(self.spinBoxComponentRadius, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_7.setMinimumSize(QtCore.QSize(140, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 2, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_4, 2, 0, 1, 1)
        self.groupBoxFixedSize = QtWidgets.QGroupBox(parent=self.frame_3)
        self.groupBoxFixedSize.setStyleSheet("")
        self.groupBoxFixedSize.setFlat(False)
        self.groupBoxFixedSize.setCheckable(True)
        self.groupBoxFixedSize.setChecked(False)
        self.groupBoxFixedSize.setObjectName("groupBoxFixedSize")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxFixedSize)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_31 = QtWidgets.QFrame(parent=self.groupBoxFixedSize)
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName("frame_31")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_31)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_31)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.frame_31)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.spinBoxSizeX = QtWidgets.QSpinBox(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxSizeX.sizePolicy().hasHeightForWidth())
        self.spinBoxSizeX.setSizePolicy(sizePolicy)
        self.spinBoxSizeX.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBoxSizeX.setMinimum(100)
        self.spinBoxSizeX.setMaximum(20000)
        self.spinBoxSizeX.setProperty("value", 5000)
        self.spinBoxSizeX.setObjectName("spinBoxSizeX")
        self.gridLayout_5.addWidget(self.spinBoxSizeX, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 1, 1, 1)
        self.spinBoxSizeY = QtWidgets.QSpinBox(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxSizeY.sizePolicy().hasHeightForWidth())
        self.spinBoxSizeY.setSizePolicy(sizePolicy)
        self.spinBoxSizeY.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBoxSizeY.setMinimum(100)
        self.spinBoxSizeY.setMaximum(20000)
        self.spinBoxSizeY.setProperty("value", 5000)
        self.spinBoxSizeY.setObjectName("spinBoxSizeY")
        self.gridLayout_5.addWidget(self.spinBoxSizeY, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_31, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBoxFixedSize, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)

        self.retranslateUi(SettingDialog)
        self.buttonBoxDialog.accepted.connect(SettingDialog.accept) # type: ignore
        self.buttonBoxDialog.rejected.connect(SettingDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingDialog)

    def retranslateUi(self, SettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingDialog.setWindowTitle(_translate("SettingDialog", "Setting Dialog"))
        self.pushButtonReset.setText(_translate("SettingDialog", "Reset"))
        self.groupBoxAutoCrop.setTitle(_translate("SettingDialog", "Auto Crop"))
        self.label.setText(_translate("SettingDialog", "Max Side Length (Pixel) : "))
        self.label_4.setText(_translate("SettingDialog", "Margin (Pixel) : "))
        self.label_6.setText(_translate("SettingDialog", "Background Color : "))
        self.label_7.setText(_translate("SettingDialog", "Component Radius : "))
        self.groupBoxFixedSize.setTitle(_translate("SettingDialog", "Fixed Size"))
        self.label_2.setText(_translate("SettingDialog", "Size (x, y) : "))
        self.label_3.setText(_translate("SettingDialog", "X"))
from src.Views.CustomWidgets.CanvasDemoGraphicsView import CanvasDemoGraphicsView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingDialog = QtWidgets.QDialog()
    ui = Ui_SettingDialog()
    ui.setupUi(SettingDialog)
    SettingDialog.show()
    sys.exit(app.exec())
